modLoader = "javafml"
loaderVersion = "${neoforge_loader_range}"
license = "CC BY-NC-ND 4.0"
issueTrackerURL = "https://github.com/tristankechlo/ImprovedVanilla/issues"
showAsResourcePack = false

[[mods]]
    modId = "improvedvanilla"
    version = "${version}"
    displayName = "Improved Vanilla"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/improved-vanilla"
    logoFile = "pack.png"
    authors = "Buecher_wurm"
    description = '''small changes/additions to make the gameplay a little bit more pleasant/enjoyable'''
    displayTest = "IGNORE_SERVER_VERSION" #optional

[[mixins]]
    config = "improvedvanilla.mixins.json"

[[dependencies.improvedvanilla]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neoforge_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.improvedvanilla]]
    modId = "minecraft"
    type = "required"
    versionRange = "${version_range}"
    ordering = "NONE"
    side = "BOTH"
